# pretrain: '/mnt/iMVR/sudhanshu/Projects/ActionCLIP/output/plovad_mby140/asl/clip_k400/ViT-B/16/mby140_fold{fold}/fold{fold}/model_best.pt'
# Example after formatting: '/mnt/iMVR/sudhanshu/Projects/ActionCLIP/output/plovad_mby140/asl/clip_k400/ViT-B/16/mby140_fold0/fold0/model_best.pt'
pretrain: '/mnt/iMVR/sudhanshu/Projects/ActionCLIP/output/plovad/bce/clip_k400/ViT-B/16/mby140_fold1/fold/model_best.pt'
seed: 1024
data:
    dataset: mby140
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 16
    workers: 16
    gpus: 4
    num_classes: 3
    image_tmpl: 'img_{:08d}.jpg'
    val_list: 'lists/mby140/fold0/mb_test.txt' #
    label_list: 'lists/mby140_labels.csv'
    index_bias: 1
    input_size: 224
    random_shift: False
    prompt_source: ''
    prompt_mix_alpha: 0.5
    prompt_prefix: 8
    prompt_postfix: 8
    prompt_std_init: 0.02
    thresholds: [0.5, 0.5, 0.5]  # [bleeding, mechanical_injury, thermal_injury]
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    bn_momentum: 0.1
    consensus_type: avg
    type: clip_k400
    sim_header: "Transf"   #Transf   meanP  LSTM  Conv_1D  Transf_cls
    joint: False
    describe:
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1
